# Generated by Django 5.1.3 on 2024-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='')),
                ('price', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('rating', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('genre', models.TextField(blank=True, default='')),
                ('language', models.TextField(blank=True, default='')),
                ('release_date', models.TextField(blank=True, default='')),
                ('publisher', models.TextField(blank=True, default='')),
                ('developer', models.TextField(blank=True, default='')),
                ('features', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
